name: Planet
version: '1.0-SNAPSHOT'
main: fr.myriapod.milkywayexplorer.Main
api-version: '1.21.1'
authors: [ Enlaniel,myriapod ]
description: c'est un bordel pour l'instant

commands:
  ship:
    description: generate a ship for user at 0 100 0
    permission: debug.ship
  gen:
    permission: debug.gen
  goto:
    description: gives momentum to user's ship (the user needs a ship...)
    permission: debug.goto
  debug:
    description: Do what ever you want with this...
    permission: debug.debug


permissions:
  debug.*:
    default: op